libmtsi : textsynthinterface.cpp
	g++ textsynthinterface.cpp `pkg-config --cflags --libs mtsynth`  -I/home/gaffordb/new_mts/MapTextSynthesizer/inc -shared -fPIC -Wno-write-strings -lpthread -o libmtsi.so
